### ISSUE TITLE
n value overflow issue

### ISSUE THREAD

**Issue by plCas** [yukt/aggRSquare#2]
Hi Yukt,

This program is really helpful. 
However, when I have too many SNPs in a bin, it makes the "Gold.MAF" and "Imputed.MAF" return negative values. 
I found that this might be caused by an overflow in the n values. 
After I changed "int n" to "uint65_t n" in aggBin.h, it returned normal results.

Will this change cause any other problems that I haven't noticed?

Thanks.

**Comment by yukt** [comment]
The changes you made shall work well.

I have changed the integer type for number of variants from int to unsigned long. Please let me know if there is any further questions.
